config/routes.rb
Rails.application.routes.draw do
  get 'shared/_alert'
  get 'shared/_footer'
  get 'shared/_header'
  get 'shared/_nav'
  root 'pages#welcome'
  #get 'pages/welcome'
  #get 'pages/privacy_policy'
  #get 'pages/cookie_policy'
  #get 'pages/terms_of_use'
  get "terms_of_use", to: "pages#terms_of_use"
  get "privacy_policy", to: "pages#privacy_policy"
  get "cookie_policy", to: "pages#cookie_policy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def privacy_policy
  end

  def cookie_policy
  end

  def terms_of_use
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def _alert
  end

  def _footer
  end

  def _header
  end

  def _nav
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdynakUniversity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/cookie_policy.html.erb
<h1>Edynak University Cookie Policy</h1>
<%= link_to "Welcome", root_path %>
<%= link_to "Terms Of Use", terms_of_use_path %>
<%= link_to "Privacy Policy", privacy_policy_path %>

app/views/pages/privacy_policy.html.erb
<h1>Edynak University Privacy Policy</h1>
<%= link_to "Welcome", root_path %>
<%= link_to "Terms Of Use", terms_of_use_path %>
<%= link_to "Cookie Policy", cookie_policy_path %>

app/views/pages/terms_of_use.html.erb
<h1>Edynak University Terms Of Use</h1>
<%= link_to "Welcome", root_path %>
<%= link_to "Privacy Policy", privacy_policy_path %>
<%= link_to "Cookie Policy", cookie_policy_path %>

app/views/pages/welcome.html.erb
<div class="card text-center">
  <div class="card-header">
    Welcome to Edynak University
  </div>
  <div class="card-body">
    <h5 class="card-title">Trusted by millions as their preferred online learning platform</h5>
    <p class="card-text">Please register an account or login to continue</p>
    <a href="#" class="btn btn-warning"><i class="fas fa-registered"></i>Sign Up</a><a href="#" class="btn btn-primary"><i class="fas fa-sign-in-alt"></i>Login
</a>
  </div>
  <div class="card-footer text-muted">
    <%= link_to "Terms Of Use", terms_of_use_path %>
    <%= link_to "Privacy Policy", privacy_policy_path %>
    <%= link_to "Cookie Policy", cookie_policy_path %>
  </div>
</div>

app/views/shared/_alert.html.erb
<h1>Shared#_alert</h1>
<p>Find me in app/views/shared/_alert.html.erb</p>

app/views/shared/_footer.html.erb
<div class="container"><h5>&copy;Edynak University 2021, &reg;Edynak University 2021, &#153;Edynak University 2021</h5></div>

app/views/shared/_header.html.erb
<%= render 'shared/nav' %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">EdynakU</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>